//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace epcalipers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("epcalipers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open {0} from disk..
        /// </summary>
        internal static string couldNotOpenFileErrorText {
            get {
                return ResourceManager.GetString("couldNotOpenFileErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resize image.
        /// </summary>
        internal static string couldNotResizeText {
            get {
                return ResourceManager.GetString("couldNotResizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening file.  Exception: .
        /// </summary>
        internal static string errorOpeningFileText {
            get {
                return ResourceManager.GetString("errorOpeningFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string errorTitleText {
            get {
                return ResourceManager.GetString("errorTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure QT.
        /// </summary>
        internal static string measureQTText {
            get {
                return ResourceManager.GetString("measureQTText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure one or more RR intervals.
        /// </summary>
        internal static string measureRRForQtcMessageText {
            get {
                return ResourceManager.GetString("measureRRForQtcMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Image Open.
        /// </summary>
        internal static string noImageOpenTitleText {
            get {
                return ResourceManager.GetString("noImageOpenTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image is open so how can you print?.
        /// </summary>
        internal static string noImageToPrintText {
            get {
                return ResourceManager.GetString("noImageToPrintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image is open so how can you save?.
        /// </summary>
        internal static string noImageToSaveText {
            get {
                return ResourceManager.GetString("noImageToSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweak {0} with arrow or ctrl-arrow keys.  Right-click to tweak a different component..
        /// </summary>
        internal static string tweakText {
            get {
                return ResourceManager.GetString("tweakText", resourceCulture);
            }
        }
    }
}
