//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPCalipersCore.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color CaliperColor {
            get {
                return ((global::System.Drawing.Color)(this["CaliperColor"]));
            }
            set {
                this["CaliperColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color HighlightColor {
            get {
                return ((global::System.Drawing.Color)(this["HighlightColor"]));
            }
            set {
                this["HighlightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int LineWidth {
            get {
                return ((int)(this["LineWidth"]));
            }
            set {
                this["LineWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000 msec")]
        public string HorizontalCalibration {
            get {
                return ((string)(this["HorizontalCalibration"]));
            }
            set {
                this["HorizontalCalibration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10 mm")]
        public string VerticalCalibration {
            get {
                return ((string)(this["VerticalCalibration"]));
            }
            set {
                this["VerticalCalibration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int NumberOfIntervalsMeanRR {
            get {
                return ((int)(this["NumberOfIntervalsMeanRR"]));
            }
            set {
                this["NumberOfIntervalsMeanRR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NumberOfIntervalsQtc {
            get {
                return ((int)(this["NumberOfIntervalsQtc"]));
            }
            set {
                this["NumberOfIntervalsQtc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bazett")]
        public string DefaultQTcFormula {
            get {
                return ((string)(this["DefaultQTcFormula"]));
            }
            set {
                this["DefaultQTcFormula"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WindowOnTopWhenTransparent {
            get {
                return ((bool)(this["WindowOnTopWhenTransparent"]));
            }
            set {
                this["WindowOnTopWhenTransparent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("To Integer")]
        public string RoundTo {
            get {
                return ((string)(this["RoundTo"]));
            }
            set {
                this["RoundTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoPositionText {
            get {
                return ((bool)(this["AutoPositionText"]));
            }
            set {
                this["AutoPositionText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center Above")]
        public string TimeCaliperTextPosition {
            get {
                return ((string)(this["TimeCaliperTextPosition"]));
            }
            set {
                this["TimeCaliperTextPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public string AmplitudeCaliperTextPosition {
            get {
                return ((string)(this["AmplitudeCaliperTextPosition"]));
            }
            set {
                this["AmplitudeCaliperTextPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RecalibrateOnChangePDFPage {
            get {
                return ((bool)(this["RecalibrateOnChangePDFPage"]));
            }
            set {
                this["RecalibrateOnChangePDFPage"] = value;
            }
        }
    }
}
